spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin 
    password: admin
    url: jdbc:postgresql://localhost/ktd
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      platform: postgres
      #mode: always
      continue-on-error: true
server:
  port : 8083

 
 
 
  
  
